# Generated by Django 2.1.7 on 2021-06-06 19:53

import controlls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=140)),
                ('postImg', models.ImageField(blank=True, null=True, upload_to=controlls.models.filepath)),
            ],
        ),
    ]
